spring:
  application:
    name: service-java

  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
